### ISSUE TITLE
Build simple program | with any language

### ISSUE THREAD

**Issue by wafarifki** [wafarifki/Hacktoberfest_2021#1]
Step By Step:

- star and fork this repo
- build your simple arithmetic program using any language you like in our Arithmetic folder and give name your simple arithmetic - - program with your username
- add your name in CONTRIBUTING.md
- pull request
- done
- Thank you for participate with this repo. let's connect with me by following me in github.

**Comment by YushChaudhary** [comment]
hey let me start this one.

**Comment by wafarifki** [comment]
> hey let me start this one.

okay sir, try it..

**Comment by YushChaudhary** [comment]
#4  I thinks this will be good.

**Comment by wafarifki** [comment]
> #4 I thinks this will be good.

xixixi urwel bro :smiley:

**Comment by Suyog57** [comment]
Hey, should I try this?

**Comment by wafarifki** [comment]
> Hey, should I try this?

yes if you want to participate in hacktoberfest 2021 event you can do it with this repo

**Comment by Mayurishinde27** [comment]
Hello @wafarifki, i would like to work on this issue.Can you please assign this to me?

**Comment by wafarifki** [comment]
> Hello @wafarifki, i would like to work on this issue.Can you please assign this to me?

yes...i can

**Comment by wahidari** [comment]
repositorynya belum diberi topik **hacktoberfest** mas, jadi tidak terdeteksi

![image](https://user-images.githubusercontent.com/17881884/135782036-d0d5b0b3-b4a8-4e4a-9d88-b629c0d2813d.png)

**Comment by wafarifki** [comment]
> repositorynya belum diberi topik **hacktoberfest** mas, jadi tidak terdeteksi
> 
> ![image](https://user-images.githubusercontent.com/17881884/135782036-d0d5b0b3-b4a8-4e4a-9d88-b629c0d2813d.png)

wait mas..

**Comment by snehashukkla** [comment]
@wafarifki i would like to contribute to this ,could you please assign this to me

**Comment by wafarifki** [comment]
> @wafarifki i would like to contribute to this ,could you please assign this to me

yes i can, please wait bro

**Comment by satyam-mahajan** [comment]
Hii , I am able to fix the issue in a optimal way. Please assign to me.
Thanking you...!!!

**Comment by wafarifki** [comment]
> Hii , I am able to fix the issue in a optimal way. Please assign to me. Thanking you...!!!

done, please fix bro

**Comment by Crazy2code15** [comment]
hi @wafarifki , I want to work on this issue. can you please assign this to me.

**Comment by wafarifki** [comment]
> hi @wafarifki , I want to work on this issue. can you please assign this to me.

yes i has been merge & asign your pr

**Comment by zulfikar-dityaa** [comment]
please add topic 
- hacktoberfest21
- hacktoberfest2021
- hacktoberfest
- hacktoberfest-accepted

**Comment by Crazy2code15** [comment]
> > hi @wafarifki , I want to work on this issue. can you please assign this to me.
> 
> yes i has been merge & asign your pr

Thank you @wafarifki , I have added 4 more codes of python please merge them too

**Comment by zulfikar-dityaa** [comment]
> > please add topic
> > 
> > * hacktoberfest21
> > * hacktoberfest2021
> > * hacktoberfest
> done.
thanks

**Comment by wafarifki** [comment]
> > > please add topic
> > > 
> > > * hacktoberfest21
> > > * hacktoberfest2021
> > > * hacktoberfest
> > >   done.
> > >   thanks

urwell bro

**Comment by maleeshasilva** [comment]
hi Can I work On it ?

**Comment by wafarifki** [comment]
> reponya udah lu daftarin blm sih ? di profile lu edit, lu sebagai maintaner juga.

gausah lu kasih tau. emang gua bocah tk. 

sebelum lu nyuruh udah gua lakuin sbg maintaner

**Comment by Ikhari** [comment]
di about ablm ada label

**Comment by wafarifki** [comment]
> di about blm ada label

nih lu gua assign aja deh lu edit nih reponya

**Comment by Ikhari** [comment]
> > > > reponya udah lu daftarin blm sih ? di profile lu edit, lu sebagai maintaner juga.
> > > 
> > > 
> > > gausah lu kasih tau. emang gua bocah tk.
> > > sebelum lu nyuruh udah gua lakuin sbg maintaner
> > 
> > 
> > yaampun gua cuman nanya, jawabnya gitu amat.
> 
> ya kalo nanya gausah pake sih. kesan nya nyolot gitu kan...
> 
> nanya biasa aja kan gua jawab nya juga sopan banget.
> 
> cek deh komen gua diatas. ada ga yang begini. kalo dari orang nya nanya enak gua jawab lebih enak bang..

maaf banget pak, kalo kata sih bisa buat lu tersinggung, gua gak ada maksud nyolot.

**Comment by wafarifki** [comment]
> > > > > reponya udah lu daftarin blm sih ? di profile lu edit, lu sebagai maintaner juga.
> > > > 
> > > > 
> > > > gausah lu kasih tau. emang gua bocah tk.
> > > > sebelum lu nyuruh udah gua lakuin sbg maintaner
> > > 
> > > 
> > > yaampun gua cuman nanya, jawabnya gitu amat.
> > 
> > 
> > ya kalo nanya gausah pake sih. kesan nya nyolot gitu kan...
> > nanya biasa aja kan gua jawab nya juga sopan banget.
> > cek deh komen gua diatas. ada ga yang begini. kalo dari orang nya nanya enak gua jawab lebih enak bang..
> 
> maaf banget pak, kalo kata sih bisa buat lu tersinggung, gua gak ada maksud nyolot.

iya bang..gua juga minta maaf ya bang 🙏sorry banget ya bang..🙏🙏🤝

**Comment by wafarifki** [comment]
> Nih coba tambahin label di about pak, gua gak bisa soalnya. https://www.youtube.com/watch?v=znPdP0o79mU

done bang dah gua tambah tu bang🤝

**Comment by Ikhari** [comment]
siip pak, udah bisa, udah kehitung di profile 🙏
