### ISSUE TITLE
Project not participating

### ISSUE THREAD

**Issue by zulfikar-dityaa** [wafarifki/Hacktoberfest_2021#145]
Hacktoberfest is open to everyone in our global community. Whether you’re a seasoned contributor or looking for projects to contribute to for the first time, you’re welcome to participate.

Pull requests can be made in any participating GitHub or GitLab hosted repository/project. Look for the 'hacktoberfest' topic to know if a repository/project is participating in Hacktoberfest. Pull requests must be approved by a maintainer of the repository/project to count.

You can sign up anytime between October 1 and October 31. Just be sure to sign up on the official Hacktoberfest website for your pull requests to count.

**Comment by wafarifki** [comment]
okay thank you for info🙏

**Comment by zulfikar-dityaa** [comment]
> okay thank you for info🙏

ok
